### ISSUE TITLE
Streaming and caching

### ISSUE THREAD

**Issue by bizibizi** [NoonPacific/NPAudioStream#4]
Is possible do such things with the library?

start playing .mp3 from url immediately (like streaming or streaming)
cache it and track caching progress during it's playback
save cached file to local storage

**Comment by AlexGivens** [comment]
Currently there is no support in this library to cache incoming audio. We used this library to stream from SoundCloud, which did not allow us to cache audio for legal reasons. However, the feature would be welcome!
