### ISSUE TITLE
NPAudioStream 301 redirect url error

### ISSUE THREAD

**Issue by dilek0402** [NoonPacific/NPAudioStream#7]
Hi,
Our application is a radio application. We are playing http hls links. There is cluster semantics on the server side. When the broadcast starts, the server receives a redirect URL and is directed to another server, but iOS is not redirected and the broadcast is stopped. How can I solve this problem?

Thanks

**Comment by AlexGivens** [comment]
NPAudioStream was not built with live streaming in mind, however let's see if we can make it work. Is the redirect URL you mentioned able to be fed into the library once available?

**Comment by dilekeminoglu** [comment]
Yes, I have check the url into the library once a time,It's played.The url did not work in the scenario I mentioned above.

**Comment by AlexGivens** [comment]
Could you provide code to clarify? I'm confused about how you are passing in the stream URLs.
